version: '3'
services:
  #######################################
  # TapIt Application
  #######################################
  app:
    build:
      context: ./tapit-build/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
    restart: always

  #######################################
  # Postgres server
  #######################################
  postgres-tapit:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tapit
      - POSTGRES_PASSWORD=secret-tapit-password
      - POSTGRES_DB=tapit

